export { default as SignUp } from './SignUp.vue';
export { default as SignIn } from './SignIn.vue';
export { default as ForgetPassword } from './ForgetPassword.vue';
export { default as ResetPassword } from './ResetPassword.vue';
export { default as Dashboard } from './Dashboard.vue';
export { default as Notfound } from './Notfound.vue';
export { default as Admins } from './Admins.vue';
export { default as Category } from './Category.vue';
export { default as Customers } from './Customers.vue';